build:
	docker build --compress --no-cache -t jodafons/saphyra:latest .
	docker build --compress -t jodafons/saphyra:base .
push:
	docker push jodafons/saphyra:latest
	docker push jodafons/saphyra:base

